apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: sock-shop
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer