name: Deploy ArgoCD Application
on:
  workflow_dispatch:
jobs:
  deploy-argocd-app:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Configure AWS and Kubecontext
      run: |
        aws eks update-kubeconfig --region us-east-1 --name primary-eks
    - name: Apply ArgoCD Application
      run: |
        kubectl apply -f automation/argocd-apps/app-blue.yaml
        kubectl apply -f automation/argocd-apps/app-green.yaml