name: Terraform Infrastructure Deployment

on:
  workflow_dispatch:

env:
  TF_DIR: terraform

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.12.2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Terraform Init
      working-directory: ${{ env.TF_DIR }}
      run: terraform init

    - name: Terraform Plan
      working-directory: ${{ env.TF_DIR }}
      run: terraform plan

    - name: Terraform Apply
      working-directory: ${{ env.TF_DIR }}
      run: terraform apply -auto-approve
    
    - name: Extract ECR repo URI from Terraform
      id: ecr
      run: |
        echo "ECR_REPO=$(terraform output -raw ecr_repo_url)" >> $GITHUB_ENV
